import { NextResponse } from "next/server";
import { auth } from "../../../../../../auth";
import { documentStorage } from "../../../../../../lib/document-storage";
import { hashSignatureTransferToken, transferIsActive } from "../../../../../../lib/document-studio-transfer";
import { prisma } from "../../../../../../lib/prisma";

async function ownedSignatureItem(id: string, userId: string, token: string | null) { const item = await prisma.documentStudioTransferItem.findUnique({ where: { id }, include: { session: true } }); return item && token && item.session.userId === userId && item.session.tokenHash === hashSignatureTransferToken(token) ? item : null; }
export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await auth(); const { id } = await params; if (!user?.user?.id) return NextResponse.json({ error: "Not found" }, { status: 404 }); const item = await ownedSignatureItem(id, user.user.id, request.headers.get("x-signature-transfer-token")); if (!item || item.consumedAt || !transferIsActive(item.session)) return NextResponse.json({ error: "Not found" }, { status: 404 }); const stored = await documentStorage().read(item.storageKey); if (!stored) return NextResponse.json({ error: "Unavailable" }, { status: 404 }); return new NextResponse(stored.body, { headers: { "Content-Type": "image/png", "Cache-Control": "private, no-store" } }); }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await auth(); const { id } = await params; if (!user?.user?.id) return NextResponse.json({ error: "Not found" }, { status: 404 }); const item = await ownedSignatureItem(id, user.user.id, request.headers.get("x-signature-transfer-token")); if (!item || item.consumedAt || !transferIsActive(item.session)) return NextResponse.json({ error: "Not found" }, { status: 404 }); const updated = await prisma.documentStudioTransferItem.updateMany({ where: { id, consumedAt: null }, data: { consumedAt: new Date() } }); if (updated.count !== 1) return NextResponse.json({ error: "Already consumed" }, { status: 409 }); await documentStorage().delete(item.storageKey); return NextResponse.json({ ok: true }); }
