import Link from "next/link";

const steps = [
  ["01", "Select your service", "Choose the immigration service you need."],
  ["02", "Pay €100 assessment fee", "Start with a professional assessment."],
  ["03", "Receive your assessment", "Your professional reviews your situation and provides their assessment."],
  ["04", "Decide whether to proceed", "Continue only after reviewing your assessment."],
  ["05", "Manage your case online", "Upload documents, communicate with your professional and track progress."],
] as const;

const features = [
  ["progress", "Case progress tracking", "See completed tasks, current status and the next action for your case."],
  ["upload", "Secure document uploads", "Keep client documents organised within your private case workspace."],
  ["message", "Professional messaging", "Ask questions and keep case communication together in one place."],
  ["payment", "Payment tracking", "See your assessment fee and remaining payment status clearly."],
  ["assessment", "Assessment results", "Review your professional's assessment before deciding whether to continue."],
  ["document", "Professional documents", "Access documents prepared and released by your professional."],
] as const;

export default function HomePage() {
  return <main className="min-h-screen bg-white text-[#0B1F3A]">
    <header className="sticky top-0 z-40 border-b border-[#DCE5F0] bg-white/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
        <Link href="/" aria-label="CaseWiser home" className="flex items-center gap-3 text-xl font-bold tracking-tight"><BrandMark /><span>CaseWiser</span></Link>
        <nav aria-label="Main navigation" className="hidden items-center gap-8 text-sm font-semibold text-[#3E526B] md:flex"><a href="#how-it-works" className="transition hover:text-[#003580]">How it works</a><a href="#services" className="transition hover:text-[#003580]">Services</a><Link href="/sign-in" className="transition hover:text-[#003580]">Sign in</Link><Link href="/services" className="rounded-lg bg-[#003580] px-4 py-2.5 text-white shadow-sm transition hover:bg-[#002B68]">Start assessment</Link></nav>
        <div className="flex items-center gap-2 md:hidden"><Link href="/sign-in" className="px-2 py-2 text-sm font-semibold">Sign in</Link><Link href="/services" className="rounded-lg bg-[#003580] px-3 py-2 text-sm font-semibold text-white">Start</Link></div>
      </div>
    </header>

    <section className="relative overflow-hidden border-b border-[#DCE5F0] bg-[#F4F8FC]">
      <div className="pointer-events-none absolute right-[-10rem] top-[-12rem] h-[32rem] w-[32rem] rounded-full border-[5rem] border-white/70" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 sm:py-24 lg:grid-cols-[1.12fr_.88fr] lg:px-8 lg:py-32">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-[#B9CEE6] bg-white px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-[#003580]"><span className="h-2 w-2 rounded-full bg-[#003580]" />Finland residence permit services</div><p className="mt-7 text-sm font-bold tracking-wide text-[#003580]">CaseWiser</p><h1 className="mt-3 max-w-3xl text-4xl font-bold leading-[1.08] tracking-[-.035em] sm:text-5xl lg:text-6xl">Immigration support, managed from one place</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#52677F]">Get your case assessed by an immigration professional, upload your documents securely, make payments and track your case online.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/services" className="rounded-lg bg-[#003580] px-6 py-3.5 text-center font-semibold text-white shadow-[0_10px_28px_rgba(0,53,128,.2)] transition hover:bg-[#002B68]">Start your assessment <span aria-hidden="true">→</span></Link><Link href="/sign-in" className="rounded-lg border border-[#B9C7D8] bg-white px-6 py-3.5 text-center font-semibold transition hover:border-[#003580] hover:text-[#003580]">Sign in</Link></div><p className="mt-5 text-sm text-[#63778E]">Independent professional immigration support. CaseWiser is not affiliated with the Finnish government.</p></div>
        <div className="rounded-3xl border border-[#C8D7E7] bg-white p-6 shadow-[0_24px_65px_rgba(11,31,58,.12)] sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#59718B]">A clear first step</p><div className="mt-5 flex items-end justify-between border-b border-[#E1E9F2] pb-6"><div><p className="text-4xl font-bold tracking-tight text-[#003580]">€100</p><p className="mt-1 font-semibold">Professional assessment</p></div><Icon name="assessment" /></div><p className="mt-6 text-lg font-semibold leading-7">Deducted from your service fee if you proceed.</p><div className="mt-6 space-y-3 text-sm text-[#52677F]"><Tick>Professional review of your situation</Tick><Tick>Clear assessment and recommended next steps</Tick><Tick>You decide whether to continue</Tick></div></div>
      </div>
    </section>

    <section id="how-it-works" className="scroll-mt-20 py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>How it works</Eyebrow><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-[-.025em] sm:text-4xl">A transparent path from assessment to completion</h2><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-[#DCE5F0] bg-[#DCE5F0] sm:grid-cols-2 lg:grid-cols-5">{steps.map(([number, title, copy]) => <article key={number} className="bg-white p-6 lg:min-h-64"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#EAF2FA] text-sm font-bold text-[#003580]">{number}</span><h3 className="mt-6 text-lg font-bold leading-6">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5B6F86]">{copy}</p></article>)}</div></div></section>

    <section id="services" className="scroll-mt-20 border-y border-[#DCE5F0] bg-[#F4F8FC] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="text-center"><Eyebrow>Finland launch services</Eyebrow><h2 className="mt-3 text-3xl font-bold tracking-[-.025em] sm:text-4xl">Straightforward services. Clear pricing.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#5B6F86]">Begin with an assessment. Pay the remaining balance only after reviewing the result and choosing to proceed.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2"><ServiceCard title="First Residence Permit" /><ServiceCard title="Residence Permit Renewal" /></div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><Eyebrow>Your workspace</Eyebrow><h2 className="mt-3 text-3xl font-bold tracking-[-.025em] sm:text-4xl">Your immigration case in one secure workspace</h2><p className="mt-4 leading-7 text-[#5B6F86]">CaseWiser brings the practical parts of your case together, so you can always see what is happening and what comes next.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{features.map(([icon, title, copy]) => <article key={title} className="rounded-2xl border border-[#DCE5F0] bg-white p-6 shadow-[0_8px_28px_rgba(11,31,58,.05)]"><Icon name={icon}/><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5B6F86]">{copy}</p></article>)}</div></div></section>

    <section className="px-5 pb-20 sm:pb-24 lg:px-8"><div className="mx-auto max-w-6xl overflow-hidden rounded-3xl bg-[#082C5C] px-6 py-12 text-white sm:px-12 sm:py-14 lg:flex lg:items-center lg:justify-between lg:gap-12"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#AFCBEA]">Not sure which service you need?</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Start with the €100 professional assessment.</h2><p className="mt-4 leading-7 text-[#D5E2F1]">Your situation can be reviewed before you decide whether to proceed with the full service.</p></div><Link href="/services" className="mt-7 inline-block shrink-0 rounded-lg bg-white px-6 py-3.5 text-center font-semibold text-[#003580] shadow-sm transition hover:bg-[#EAF2FA] lg:mt-0">Start your assessment <span aria-hidden="true">→</span></Link></div></section>

    <footer className="border-t border-[#DCE5F0] bg-[#F8FAFC]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:grid-cols-2 sm:items-end lg:px-8"><div><div className="flex items-center gap-3 text-lg font-bold"><BrandMark />CaseWiser</div><p className="mt-4 max-w-md text-sm leading-6 text-[#64778D]">Independent immigration case services designed to make assessment, documents and progress easier to manage.</p></div><div className="text-sm text-[#64778D] sm:text-right"><div className="flex flex-wrap gap-5 sm:justify-end"><a href="#how-it-works">How it works</a><a href="#services">Services</a><Link href="/professionals">Professional marketplace</Link><Link href="/sign-in">Sign in</Link></div><p className="mt-5">© 2026 CaseWiser. Not affiliated with the Finnish government.</p></div></div></footer>
  </main>;
}

function BrandMark() { return <span aria-hidden="true" className="grid h-9 w-9 place-items-center rounded-lg bg-[#003580] text-xs font-bold text-white shadow-sm">CW</span>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-sm font-bold uppercase tracking-[.16em] text-[#003580]">{children}</p>; }
function Tick({ children }: { children: React.ReactNode }) { return <p className="flex items-start gap-3"><span aria-hidden="true" className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#EAF2FA] text-xs font-bold text-[#003580]">✓</span><span>{children}</span></p>; }
function ServiceCard({ title }: { title: string }) { return <article className="flex flex-col rounded-2xl border border-[#C8D7E7] bg-white p-7 shadow-[0_12px_35px_rgba(11,31,58,.07)] sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#003580]">Finland</p><h3 className="mt-3 text-2xl font-bold">{title}</h3><div className="mt-7 border-y border-[#E1E9F2] py-5"><p className="text-3xl font-bold tracking-tight">€500 <span className="text-sm font-medium text-[#64778D]">total service fee</span></p><p className="mt-2 text-sm font-semibold text-[#3E526B]">€100 assessment + €400 if you proceed</p></div><ul className="mt-6 flex-1 space-y-3 text-sm text-[#5B6F86]"><li>Professional assessment first</li><li>Online case and document workspace</li><li>Clear progress and payment tracking</li></ul><Link href="/services" className="mt-7 rounded-lg bg-[#003580] px-5 py-3 text-center font-semibold text-white transition hover:bg-[#002B68]">Start assessment <span aria-hidden="true">→</span></Link></article>; }
function Icon({ name }: { name: string }) { const symbols: Record<string, string> = { progress: "↗", upload: "↑", message: "…", payment: "€", assessment: "✓", document: "≡" }; return <span aria-hidden="true" className="grid h-11 w-11 place-items-center rounded-xl bg-[#EAF2FA] text-lg font-bold text-[#003580]">{symbols[name] ?? "✓"}</span>; }
