"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const countries = ["Finland", "Germany", "Canada", "United Kingdom", "Australia", "Sweden"];
const services = ["Work visas", "Student visas", "Family reunification", "Residence permits", "Permanent residence", "Citizenship"];

function ArrowIcon() { return <span aria-hidden="true" className="ml-2">→</span>; }
function CheckIcon() { return <span aria-hidden="true" className="mr-3 inline-flex h-5 w-5 items-center justify-center rounded-full bg-teal-100 text-xs text-teal-700">✓</span>; }

export default function HomePage() {
  const router = useRouter();
  const [country, setCountry] = useState("");
  const [service, setService] = useState("");
  const [message, setMessage] = useState("");
  function submit(event: FormEvent) {
    event.preventDefault();
    if (!country || !service) { setMessage("Choose both a destination country and the support you need to explore professionals."); return; }
    router.push(`/professionals?country=${encodeURIComponent(country)}&service=${encodeURIComponent(service)}`);
  }
  return <main>
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-8"><a href="#top" className="flex items-center gap-2 text-xl font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-ocean text-sm text-white">M</span>Migrate</a><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#how-it-works">How it works</a><a href="#destinations">Destinations</a><a href="#trust">Trust & safety</a></nav><a href="#professionals" className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold hover:bg-slate-50">For professionals</a></header>
    <section id="top" className="relative overflow-hidden bg-mist"><div className="absolute -right-20 top-0 h-80 w-80 rounded-full bg-teal-100/70 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="mb-5 text-sm font-bold uppercase tracking-[0.18em] text-ocean">Immigration guidance, connected</p><h1 className="text-4xl font-bold leading-tight tracking-tight text-ink sm:text-5xl lg:text-6xl">Find the Right Immigration Professional for Your Journey</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Connect with verified immigration lawyers and accredited advisers for visa and residence permit support—across borders, in a language you understand.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#destinations" className="rounded-lg bg-ocean px-5 py-3 text-center font-semibold text-white shadow-soft hover:bg-[#0f5b7d]">Find an Immigration Professional<ArrowIcon /></a><a href="#professionals" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-center font-semibold hover:bg-slate-50">Join as a Professional</a></div><p className="mt-6 text-sm text-slate-500">For informational matching only. Professionals provide their own services and advice.</p></div>
      <form onSubmit={submit} className="self-center rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><p className="text-sm font-semibold text-slate-500">START YOUR SEARCH</p><h2 className="mt-2 text-2xl font-bold">Where are you headed?</h2><div className="mt-5 space-y-4"><label className="block text-sm font-semibold">Destination country<select value={country} onChange={(e) => setCountry(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-3 font-normal text-slate-600"><option value="">Select a country</option>{countries.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm font-semibold">What do you need help with?<select value={service} onChange={(e) => setService(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-3 font-normal text-slate-600"><option value="">Select a service</option>{services.map((item) => <option key={item}>{item}</option>)}</select></label>{message && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{message}</p>}<button className="w-full rounded-lg bg-ink px-4 py-3 font-semibold text-white hover:bg-slate-800">Explore professionals <ArrowIcon /></button></div></form></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-6 py-20 lg:px-8"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-ocean">A clearer way forward</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Support that starts with the right match.</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[["01", "Tell us your goal", "Choose a country and the immigration support you need."], ["02", "Compare professionals", "Review relevant expertise, languages, experience, and transparent starting prices."], ["03", "Request a consultation", "Send your request and decide who feels right for your journey."]].map(([number, title, copy]) => <div key={number} className="border-t-2 border-ocean pt-5"><span className="text-sm font-bold text-ocean">{number}</span><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></div>)}</div></section>
    <section id="destinations" className="bg-ink py-20 text-white"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-200">Explore by destination</p><div className="mt-3 flex flex-wrap items-end justify-between gap-6"><h2 className="text-3xl font-bold tracking-tight">Popular places to begin</h2><a href="#top" className="font-semibold text-teal-200">View all destinations <ArrowIcon /></a></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{countries.map((item, index) => <a href="#top" key={item} className="group rounded-xl border border-white/15 bg-white/5 p-5 transition hover:bg-white/10"><p className="text-xs font-bold uppercase tracking-widest text-teal-200">Destination {String(index + 1).padStart(2, "0")}</p><p className="mt-8 text-xl font-semibold">{item}<span className="float-right transition group-hover:translate-x-1">→</span></p></a>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-ocean">Common needs</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Find support for every stage.</h2><p className="mt-5 leading-7 text-slate-600">From an initial visa plan to a complex appeal, search for professionals whose practice matches your situation.</p></div><div className="grid gap-3 sm:grid-cols-2">{services.map((item) => <a href="#top" key={item} className="flex items-center justify-between rounded-xl border border-slate-200 p-4 font-semibold hover:border-ocean hover:text-ocean">{item}<span>→</span></a>)}</div></div></section>
    <section id="trust" className="bg-[#EDF7F7]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-ocean">Built around confidence</p><h2 className="mt-3 text-3xl font-bold tracking-tight">A more transparent way to choose help.</h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Migrate is designed to make the first steps less uncertain—without replacing your own judgement or a professional&apos;s independent advice.</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-xl bg-white p-5"><CheckIcon /><span className="font-bold">Professional profiles</span><p className="mt-3 text-sm leading-6 text-slate-600">See qualifications, experience, focus countries, and languages in one place.</p></div><div className="rounded-xl bg-white p-5"><CheckIcon /><span className="font-bold">Clearer comparisons</span><p className="mt-3 text-sm leading-6 text-slate-600">Compare available services and starting prices before you reach out.</p></div></div></div></section>
    <section id="professionals" className="mx-auto max-w-5xl px-6 py-20 text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-ocean">For immigration professionals</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-bold tracking-tight">Build meaningful connections with clients seeking your expertise.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-slate-600">Create a focused profile, describe your practice, and receive suitable client requests.</p><a href="#top" className="mt-8 inline-block rounded-lg bg-ocean px-5 py-3 font-semibold text-white shadow-soft hover:bg-[#0f5b7d]">Apply to join Migrate <ArrowIcon /></a></section>
    <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-6 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>© 2026 Migrate. A learning prototype.</p><p>Not legal advice. Credentials and outcomes should be independently verified.</p></div></footer>
  </main>;
}
