"use client";

import { useEffect, useRef, useState } from "react";
import { PDFCheckBox, PDFDocument, PDFDropdown, PDFOptionList, PDFRadioGroup, PDFTextField, StandardFonts, rgb } from "pdf-lib";
import { movePdfPage, normalizedPlacement, parsePdfPageSelection, removePdfPage } from "../lib/pdf-studio-editor";

type FormField = { name: string; kind: "text" | "checkbox" | "radio" | "select"; value: string | boolean; options?: string[] };
type TextPlacement = { id: string; text: string; page: number; x: number; y: number; size: number };
type SignaturePlacement = { id: string; page: number; x: number; y: number; width: number };

async function transparentSignature(file: File) {
  const bitmap = await createImageBitmap(file); const source = document.createElement("canvas"); source.width = bitmap.width; source.height = bitmap.height;
  const context = source.getContext("2d"); if (!context) throw new Error("Image processing is unavailable."); context.drawImage(bitmap, 0, 0); bitmap.close();
  const pixels = context.getImageData(0, 0, source.width, source.height); let left = source.width; let top = source.height; let right = -1; let bottom = -1;
  for (let y = 0; y < source.height; y += 1) for (let x = 0; x < source.width; x += 1) { const offset = (y * source.width + x) * 4; const dark = Math.min(pixels.data[offset], pixels.data[offset + 1], pixels.data[offset + 2]) < 235 && pixels.data[offset + 3] > 10; if (dark) { left = Math.min(left, x); right = Math.max(right, x); top = Math.min(top, y); bottom = Math.max(bottom, y); } }
  if (right < left) throw new Error("No signature marks were detected. Try stronger lighting and darker ink.");
  const padding = Math.max(4, Math.round(Math.max(source.width, source.height) * .02)); left = Math.max(0, left - padding); top = Math.max(0, top - padding); right = Math.min(source.width - 1, right + padding); bottom = Math.min(source.height - 1, bottom + padding);
  const output = document.createElement("canvas"); output.width = right - left + 1; output.height = bottom - top + 1; const outputContext = output.getContext("2d"); if (!outputContext) throw new Error("Image processing is unavailable."); outputContext.drawImage(source, left, top, output.width, output.height, 0, 0, output.width, output.height);
  const cleaned = outputContext.getImageData(0, 0, output.width, output.height); for (let offset = 0; offset < cleaned.data.length; offset += 4) { const lightness = Math.min(cleaned.data[offset], cleaned.data[offset + 1], cleaned.data[offset + 2]); if (lightness > 235) cleaned.data[offset + 3] = 0; else cleaned.data[offset + 3] = Math.max(cleaned.data[offset + 3], 255 - lightness); } outputContext.putImageData(cleaned, 0, 0);
  const blob = await new Promise<Blob>((resolve, reject) => output.toBlob((value) => value ? resolve(value) : reject(new Error("Could not create signature image.")), "image/png")); return new File([blob], "signature.png", { type: "image/png" });
}

function DrawSignature({ onUse }: { onUse: (file: File) => void }) {
  const ref = useRef<HTMLCanvasElement>(null); const drawing = useRef(false);
  const point = (event: React.PointerEvent<HTMLCanvasElement>) => { const canvas = ref.current!; const rect = canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; };
  const start = (event: React.PointerEvent<HTMLCanvasElement>) => { const canvas = ref.current!; const context = canvas.getContext("2d")!; const current = point(event); drawing.current = true; canvas.setPointerCapture(event.pointerId); context.beginPath(); context.moveTo(current.x, current.y); };
  const move = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing.current) return; const context = ref.current!.getContext("2d")!; const current = point(event); context.lineWidth = 3; context.lineCap = "round"; context.strokeStyle = "#102A43"; context.lineTo(current.x, current.y); context.stroke(); };
  const clear = () => ref.current?.getContext("2d")?.clearRect(0, 0, ref.current.width, ref.current.height);
  const use = () => ref.current?.toBlob((blob) => { if (blob) onUse(new File([blob], "drawn-signature.png", { type: "image/png" })); }, "image/png");
  return <div><canvas ref={ref} width={700} height={220} aria-label="Draw your signature" className="h-36 w-full touch-none rounded-lg border border-slate-300 bg-white" onPointerDown={start} onPointerMove={move} onPointerUp={() => { drawing.current = false; }} onPointerCancel={() => { drawing.current = false; }}/><div className="mt-2 flex gap-2"><button type="button" onClick={clear} className="rounded-lg border px-3 py-2 text-sm font-semibold">Clear</button><button type="button" onClick={use} className="rounded-lg bg-ocean px-3 py-2 text-sm font-semibold text-white">Use drawing</button></div></div>;
}

export function DocumentStudioPdfEditor({ file, onClose, onApply }: { file: File; onClose: () => void; onApply: (file: File) => void }) {
  const [pageCount, setPageCount] = useState(0); const [pages, setPages] = useState<number[]>([]); const [range, setRange] = useState(""); const [rangeError, setRangeError] = useState<string | null>(null);
  const [fields, setFields] = useState<FormField[]>([]); const [loaded, setLoaded] = useState(false); const [error, setError] = useState<string | null>(null); const [working, setWorking] = useState(false); const [previewUrl, setPreviewUrl] = useState("");
  const [texts, setTexts] = useState<TextPlacement[]>([]); const [textDraft, setTextDraft] = useState({ text: "", page: 1, x: 15, y: 20, size: 12 });
  const [signature, setSignature] = useState<File | null>(null); const [signatureUrl, setSignatureUrl] = useState<string | null>(null); const [signatureMessage, setSignatureMessage] = useState<string | null>(null); const [signaturePlacements, setSignaturePlacements] = useState<SignaturePlacement[]>([]); const [signatureDraft, setSignatureDraft] = useState({ page: 1, x: 55, y: 72, width: 28 }); const [previewPage, setPreviewPage] = useState(1);

  useEffect(() => { const url = URL.createObjectURL(file); setPreviewUrl(url); void (async () => { try { const pdf = await PDFDocument.load(await file.arrayBuffer()); const count = pdf.getPageCount(); setPageCount(count); setPages(Array.from({ length: count }, (_, index) => index)); setRange(`1-${count}`); const detected: FormField[] = []; for (const field of pdf.getForm().getFields()) { if (field instanceof PDFTextField) detected.push({ name: field.getName(), kind: "text", value: field.getText() ?? "" }); else if (field instanceof PDFCheckBox) detected.push({ name: field.getName(), kind: "checkbox", value: field.isChecked() }); else if (field instanceof PDFRadioGroup) detected.push({ name: field.getName(), kind: "radio", value: field.getSelected() ?? "", options: field.getOptions() }); else if (field instanceof PDFDropdown || field instanceof PDFOptionList) detected.push({ name: field.getName(), kind: "select", value: field.getSelected()[0] ?? "", options: field.getOptions() }); } setFields(detected); } catch { setError("This PDF could not be opened for editing."); } finally { setLoaded(true); } })(); return () => URL.revokeObjectURL(url); }, [file]);
  useEffect(() => { if (!signature) { setSignatureUrl(null); return; } const url = URL.createObjectURL(signature); setSignatureUrl(url); return () => URL.revokeObjectURL(url); }, [signature]);
  const selectRange = () => { try { setPages(parsePdfPageSelection(range, pageCount)); setRangeError(null); } catch (selectionError) { setRangeError(selectionError instanceof Error ? selectionError.message : "Check the page selection."); } };
  const chooseSignature = async (selected: FileList | null) => { const selectedFile = selected?.[0]; if (!selectedFile) return; setSignatureMessage("Preparing signature image…"); try { setSignature(await transparentSignature(selectedFile)); setSignatureMessage("Signature prepared with surrounding blank space removed."); } catch (signatureError) { setSignatureMessage(signatureError instanceof Error ? signatureError.message : "Could not prepare that image."); } };
  const addText = () => { if (!textDraft.text.trim() || textDraft.page < 1 || textDraft.page > pages.length) return; setTexts((current) => [...current, { id: crypto.randomUUID(), ...textDraft, text: textDraft.text.trim() }]); setTextDraft((current) => ({ ...current, text: "" })); };
  const editText = (item: TextPlacement) => { setTextDraft({ text: item.text, page: item.page, x: item.x, y: item.y, size: item.size }); setTexts((current) => current.filter((text) => text.id !== item.id)); };
  const addSignature = () => { if (!signature || signatureDraft.page < 1 || signatureDraft.page > pages.length) return; setSignaturePlacements((current) => [...current, { id: crypto.randomUUID(), ...signatureDraft }]); };
  const editSignature = (item: SignaturePlacement) => { setSignatureDraft({ page: item.page, x: item.x, y: item.y, width: item.width }); setSignaturePlacements((current) => current.filter((placement) => placement.id !== item.id)); };
  const apply = async () => { if (!pages.length) { setError("Keep at least one page."); return; } setWorking(true); setError(null); try { const source = await PDFDocument.load(await file.arrayBuffer()); const form = source.getForm(); for (const field of fields) { const pdfField = form.getField(field.name); if (pdfField instanceof PDFTextField) pdfField.setText(String(field.value)); else if (pdfField instanceof PDFCheckBox) field.value ? pdfField.check() : pdfField.uncheck(); else if (pdfField instanceof PDFRadioGroup) pdfField.select(String(field.value)); else if (pdfField instanceof PDFDropdown || pdfField instanceof PDFOptionList) pdfField.select(String(field.value)); } if (fields.length) form.flatten(); const filled = await PDFDocument.load(await source.save()); const output = await PDFDocument.create(); const copied = await output.copyPages(filled, pages); copied.forEach((page) => output.addPage(page)); const font = await output.embedFont(StandardFonts.Helvetica); for (const placement of texts) { const page = output.getPage(placement.page - 1); if (!page) continue; const position = normalizedPlacement({ page: placement.page, xPercent: placement.x, yPercent: placement.y, widthPercent: 1 }); page.drawText(placement.text, { x: page.getWidth() * position.x, y: page.getHeight() * (1 - position.y) - placement.size, size: placement.size, font, color: rgb(.06, .16, .26), maxWidth: page.getWidth() * .8 }); } if (signature && signaturePlacements.length) { const image = await output.embedPng(await signature.arrayBuffer()); for (const placement of signaturePlacements) { const page = output.getPage(placement.page - 1); if (!page) continue; const position = normalizedPlacement({ page: placement.page, xPercent: placement.x, yPercent: placement.y, widthPercent: placement.width }); const width = page.getWidth() * position.width; const height = width * image.height / image.width; page.drawImage(image, { x: Math.min(page.getWidth() - width, page.getWidth() * position.x), y: Math.max(0, page.getHeight() * (1 - position.y) - height), width, height }); } } const bytes = await output.save(); const base = file.name.replace(/\.pdf$/i, ""); onApply(new File([bytes.buffer as ArrayBuffer], `${base}-edited.pdf`, { type: "application/pdf" })); } catch { setError("The edited PDF could not be generated. Encrypted or damaged PDFs may not be editable."); } finally { setWorking(false); } };

  return <div role="dialog" aria-modal="true" aria-labelledby="pdf-editor-title" className="fixed inset-0 z-50 overflow-y-auto bg-ink/60 p-3 sm:p-6"><div className="mx-auto my-4 max-w-6xl rounded-2xl bg-mist shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between gap-4 rounded-t-2xl border-b border-slate-200 bg-white p-5"><div><p className="text-sm font-bold uppercase tracking-widest text-ocean">Browser-side PDF tools</p><h2 id="pdf-editor-title" className="mt-1 text-2xl font-bold">Edit {file.name}</h2><p className="mt-1 text-sm text-slate-600">The original file remains unchanged.</p></div><button type="button" onClick={onClose} aria-label="Close PDF editor" className="text-2xl text-slate-500">×</button></header>
    {!loaded ? <p className="p-10 text-center">Opening PDF…</p> : <div className="grid gap-5 p-5 lg:grid-cols-[1fr_1.15fr]"><div className="space-y-5">
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Split or extract pages</h3><p className="mt-1 text-sm text-slate-600">{pageCount} pages detected. Enter pages such as 1-3 or 2, 4, 6.</p><div className="mt-3 flex gap-2"><input value={range} onChange={(event) => setRange(event.target.value)} aria-label="Page selection or ranges" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2"/><button type="button" onClick={selectRange} className="rounded-lg bg-ocean px-3 py-2 font-semibold text-white">Keep pages</button></div>{rangeError && <p role="alert" className="mt-2 text-sm text-red-700">{rangeError}</p>}<div className="mt-4 space-y-2">{pages.map((page, index) => <div key={`${page}-${index}`} className="flex items-center justify-between rounded-lg bg-mist px-3 py-2 text-sm"><span><strong>Output {index + 1}</strong> · Original page {page + 1}</span><div className="flex gap-2"><button type="button" disabled={!index} onClick={() => setPages((current) => movePdfPage(current, index, -1))} className="disabled:opacity-30">Up</button><button type="button" disabled={index === pages.length - 1} onClick={() => setPages((current) => movePdfPage(current, index, 1))} className="disabled:opacity-30">Down</button><button type="button" onClick={() => setPages((current) => removePdfPage(current, index))} className="text-red-700">Remove</button></div></div>)}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Fill PDF form</h3>{fields.length ? <><p className="mt-1 text-sm text-teal-800">{fields.length} interactive {fields.length === 1 ? "field" : "fields"} detected.</p><div className="mt-4 space-y-3">{fields.map((field, index) => <label key={field.name} className="block text-sm font-semibold">{field.name}{field.kind === "checkbox" ? <input type="checkbox" checked={Boolean(field.value)} onChange={(event) => setFields((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.checked } : item))} className="ml-3"/> : field.kind === "text" ? <input value={String(field.value)} onChange={(event) => setFields((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item))} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 font-normal"/> : <select value={String(field.value)} onChange={(event) => setFields((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item))} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 font-normal"><option value="">Choose an option</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select>}</label>)}</div></> : <p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">No interactive AcroForm fields were found. This PDF is not presented as a fillable form.</p>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Add text to PDF</h3><p className="mt-1 text-sm text-slate-600">Separate manual text placement for non-interactive PDFs.</p><input value={textDraft.text} onChange={(event) => setTextDraft({ ...textDraft, text: event.target.value })} placeholder="Text to add" className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2"/><div className="mt-3 grid grid-cols-4 gap-2">{(["page", "x", "y", "size"] as const).map((name) => <label key={name} className="text-xs font-semibold capitalize">{name === "x" ? "Left %" : name === "y" ? "Top %" : name}<input type="number" min={name === "page" ? 1 : name === "size" ? 6 : 0} max={name === "page" ? pages.length : name === "size" ? 48 : 100} value={textDraft[name]} onChange={(event) => setTextDraft({ ...textDraft, [name]: Number(event.target.value) })} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div><button type="button" onClick={addText} className="mt-3 rounded-lg border border-ocean px-3 py-2 text-sm font-semibold text-ocean">Add text placement</button><div className="mt-3 space-y-1">{texts.map((text) => <div key={text.id} className="flex justify-between rounded bg-mist p-2 text-xs"><span>Page {text.page}: {text.text}</span><span className="flex gap-2"><button type="button" onClick={() => editText(text)} className="text-ocean">Edit</button><button type="button" onClick={() => setTexts((current) => current.filter((item) => item.id !== text.id))} className="text-red-700">Remove</button></span></div>)}</div></section>
    </div><div className="space-y-5">
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Document preview</h3>{previewUrl && <iframe src={previewUrl} title="Original PDF preview" className="mt-3 h-[430px] w-full rounded-lg border"/>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Signature</h3><p className="mt-1 text-sm text-slate-600">Use for this document only. This places your image; it is not a qualified or certified digital signature.</p><div className="mt-4"><DrawSignature onUse={setSignature}/></div><div className="mt-3 grid grid-cols-2 gap-2"><label className="cursor-pointer rounded-lg border p-3 text-center text-sm font-semibold">Upload signature image<input type="file" accept="image/png,image/jpeg" className="sr-only" onChange={(event) => chooseSignature(event.target.files)}/></label><label className="cursor-pointer rounded-lg border p-3 text-center text-sm font-semibold">Capture with camera<input type="file" accept="image/png,image/jpeg" capture="environment" className="sr-only" onChange={(event) => chooseSignature(event.target.files)}/></label></div>{signatureMessage && <p className="mt-2 text-xs text-slate-600">{signatureMessage}</p>}{signatureUrl && <div className="mt-4"><div className="flex h-28 items-center justify-center rounded-lg bg-slate-100"><img src={signatureUrl} alt="Prepared signature preview" className="max-h-24 max-w-full"/></div><button type="button" onClick={() => { setSignature(null); setSignaturePlacements([]); }} className="mt-2 text-sm font-semibold text-red-700">Remove signature</button><div className="mt-4 grid grid-cols-4 gap-2">{(["page", "x", "y", "width"] as const).map((name) => <label key={name} className="text-xs font-semibold capitalize">{name === "x" ? "Left %" : name === "y" ? "Top %" : name === "width" ? "Width %" : name}<input type="number" min={name === "page" ? 1 : 0} max={name === "page" ? pages.length : 100} value={signatureDraft[name]} onChange={(event) => setSignatureDraft({ ...signatureDraft, [name]: Number(event.target.value) })} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div><button type="button" onClick={addSignature} className="mt-3 rounded-lg bg-ink px-3 py-2 text-sm font-semibold text-white">Place signature</button></div>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold">Placement review</h3><label className="text-xs font-semibold">Page <select value={previewPage} onChange={(event) => setPreviewPage(Number(event.target.value))} className="ml-1 rounded border p-1">{pages.map((_, index) => <option key={index} value={index + 1}>{index + 1}</option>)}</select></label></div><div className="relative mx-auto mt-3 aspect-[.707] max-w-sm overflow-hidden rounded border bg-white shadow-inner">{texts.filter((item) => item.page === previewPage).map((item) => <span key={item.id} className="absolute whitespace-nowrap text-[10px] text-ink" style={{ left: `${item.x}%`, top: `${item.y}%`, fontSize: `${Math.max(8, item.size * .7)}px` }}>{item.text}</span>)}{signatureUrl && signaturePlacements.filter((item) => item.page === previewPage).map((item) => <img key={item.id} src={signatureUrl} alt="Signature placement" className="absolute" style={{ left: `${item.x}%`, top: `${item.y}%`, width: `${item.width}%` }}/>)}</div><div className="mt-3 space-y-1">{signaturePlacements.map((item) => <div key={item.id} className="flex justify-between rounded bg-mist p-2 text-xs"><span>Signature on page {item.page}</span><span className="flex gap-2"><button type="button" onClick={() => editSignature(item)} className="text-ocean">Edit</button><button type="button" onClick={() => setSignaturePlacements((current) => current.filter((placement) => placement.id !== item.id))} className="text-red-700">Remove</button></span></div>)}</div></section>
    </div></div>}
    {error && <p role="alert" className="mx-5 mb-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<footer className="sticky bottom-0 flex flex-col-reverse gap-2 rounded-b-2xl border-t border-slate-200 bg-white p-5 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2.5 font-semibold">Cancel</button><button type="button" onClick={apply} disabled={working || !pages.length} className="rounded-lg bg-ocean px-4 py-2.5 font-semibold text-white disabled:opacity-40">{working ? "Creating edited PDF…" : "Review complete — create new PDF"}</button></footer>
  </div></div>;
}
