"use client";

import { PointerEvent, useEffect, useMemo, useRef, useState } from "react";
import { detectScanQuad, encodeSmartScan, loadScanImage, renderSmartScan } from "../lib/smart-scan-browser";
import { clampScanPoint, defaultScanQuad, ScanFilter, ScanPoint, ScanQuad } from "../lib/smart-scan";

const cornerNames = ["topLeft", "topRight", "bottomRight", "bottomLeft"] as const;
const filters: { value: ScanFilter; label: string }[] = [{ value: "original", label: "Original" }, { value: "clean", label: "Clean" }, { value: "grayscale", label: "Grayscale" }, { value: "high-contrast", label: "High Contrast" }];

export function SmartScanEditor({ file, onClose, onApply, onRetake }: { file: File; onClose: () => void; onApply: (file: File, fitToPage: boolean) => void; onRetake?: () => void }) {
  const [image, setImage] = useState<HTMLImageElement | null>(null); const [quad, setQuad] = useState<ScanQuad | null>(null); const [detected, setDetected] = useState(false); const [filter, setFilter] = useState<ScanFilter>("original"); const [rotation, setRotation] = useState(0); const [fitToPage, setFitToPage] = useState(true); const [working, setWorking] = useState(false); const [message, setMessage] = useState("Looking for page edges…"); const frame = useRef<HTMLDivElement>(null);
  useEffect(() => { let active = true; void loadScanImage(file).then((loaded) => { if (!active) return; const result = detectScanQuad(loaded); setImage(loaded); setQuad(result.quad); setDetected(result.detected); setMessage(result.detected ? "Page edges detected. Drag any corner to adjust." : "Edges were unclear. Adjust the four corners if needed."); }).catch(() => setMessage("This image could not be opened.")); return () => { active = false; }; }, [file]);
  const previewUrl = useMemo(() => URL.createObjectURL(file), [file]); useEffect(() => () => URL.revokeObjectURL(previewUrl), [previewUrl]);
  const moveCorner = (name: typeof cornerNames[number], event: PointerEvent<HTMLButtonElement>) => { if (!image || !quad || !frame.current) return; event.currentTarget.setPointerCapture(event.pointerId); const rect = frame.current.getBoundingClientRect(); const point: ScanPoint = clampScanPoint({ x: (event.clientX - rect.left) / rect.width * image.naturalWidth, y: (event.clientY - rect.top) / rect.height * image.naturalHeight }, image.naturalWidth, image.naturalHeight); setQuad({ ...quad, [name]: point }); };
  const apply = async () => { if (!image || !quad) return; setWorking(true); setMessage("Improving page…"); try { const canvas = renderSmartScan(image, quad, rotation, filter); const result = await encodeSmartScan(canvas, file.name || "scan-page.jpg"); onApply(result, fitToPage); } catch { setMessage("The selected corners could not be processed. Adjust them and try again."); } finally { setWorking(false); } };
  const reset = () => { if (!image) return; setQuad(defaultScanQuad(image.naturalWidth, image.naturalHeight)); setDetected(false); };
  return <div role="dialog" aria-modal="true" aria-label="Smart Scan editor" className="fixed inset-0 z-50 overflow-y-auto bg-ink/70 p-3 sm:p-6"><div className="mx-auto max-w-3xl rounded-2xl bg-white p-4 shadow-xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-ocean">Smart Scan</p><h2 className="mt-1 text-xl font-bold">Improve this page</h2><p className="mt-1 text-sm text-slate-600">We’ll detect the page edges and straighten the document. You can adjust the corners before saving.</p></div><button type="button" onClick={onClose} className="rounded-lg border px-3 py-2 text-sm font-semibold">Close</button></div>
    <div ref={frame} className="relative mx-auto mt-5 max-h-[55vh] max-w-xl overflow-hidden rounded-xl bg-slate-950"><img src={previewUrl} alt="Page awaiting crop" className="block max-h-[55vh] w-full object-contain"/>{image && quad ? <svg className="pointer-events-none absolute inset-0 h-full w-full" viewBox={`0 0 ${image.naturalWidth} ${image.naturalHeight}`} preserveAspectRatio="none" aria-hidden="true"><polygon points={cornerNames.map((name) => `${quad[name].x},${quad[name].y}`).join(" ")} fill="rgba(14,116,144,.12)" stroke="#22d3ee" strokeWidth={Math.max(image.naturalWidth, image.naturalHeight) / 180}/></svg> : null}{image && quad ? cornerNames.map((name) => <button key={name} type="button" aria-label={`Adjust ${name} corner`} onPointerDown={(event) => moveCorner(name, event)} onPointerMove={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) moveCorner(name, event); }} className="absolute h-8 w-8 touch-none rounded-full border-4 border-white bg-ocean shadow" style={{ left: `${quad[name].x / image.naturalWidth * 100}%`, top: `${quad[name].y / image.naturalHeight * 100}%`, transform: "translate(-50%, -50%)" }}/>) : null}</div>
    <p role="status" className="mt-3 text-sm text-slate-600">{message}{detected ? "" : " Automatic detection was not applied."}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => setMessage("Drag the four corner handles to match the page.")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Adjust corners</button><button type="button" onClick={() => setRotation((value) => (value + 90) % 360)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Rotate 90°</button><button type="button" onClick={reset} className="rounded-lg border px-3 py-2 text-sm font-semibold">Use full page</button>{onRetake ? <button type="button" onClick={onRetake} className="rounded-lg border px-3 py-2 text-sm font-semibold">Retake</button> : null}</div><fieldset className="mt-5"><legend className="text-sm font-bold">Make this page clearer</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{filters.map((item) => <button type="button" key={item.value} onClick={() => setFilter(item.value)} aria-pressed={filter === item.value} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${filter === item.value ? "border-ocean bg-sky-50 text-ocean" : "border-slate-300"}`}>{item.label}</button>)}</div></fieldset><label className="mt-5 flex items-center gap-3 rounded-lg bg-mist p-3 text-sm font-semibold"><input type="checkbox" checked={fitToPage} onChange={(event) => setFitToPage(event.target.checked)}/> Fit to PDF page while preserving proportions</label><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-3 font-bold">Cancel</button><button type="button" disabled={!image || !quad || working} onClick={() => void apply()} className="rounded-xl bg-ocean px-4 py-3 font-bold text-white disabled:opacity-40">{working ? "Improving…" : "Use page"}</button></div></div></div>;
}
