export type ProfileService = { name: string; description: string; price: number; duration: string };
export type ClientReview = { client: string; rating: number; text: string; date: string };
export type Professional = { id: string; name: string; type: "Immigration Lawyer" | "Accredited Immigration Advisor"; country: string; jurisdiction: string; experience: number; specializations: string[]; languages: string[]; rating: number; reviews: number; price: number; description: string; qualifications: string[]; consultation: string; location?: string; tagline?: string; biography?: string; completedCases?: number; practiceCountries?: string[]; availability?: { today: boolean; thisWeek: string; next: string }; services?: ProfileService[]; clientReviews?: ClientReview[] };

export const professionals: Professional[] = [
  { id:"anna-laine", name:"Anna Laine", type:"Immigration Lawyer", country:"Finland", jurisdiction:"Finland", experience:14, specializations:["Work visas","Residence permits","Citizenship"], languages:["English","Finnish","Swedish"], rating:4.9, reviews:86, price:180, description:"Practical, clear support for professionals and families building their lives in Finland.", qualifications:["Master of Laws, University of Helsinki","Finnish Bar Association member"], consultation:"45-minute video consultation" },
  { id:"mikael-soder", name:"Mikael Söder", type:"Accredited Immigration Advisor", country:"Finland", jurisdiction:"Finland", experience:9, specializations:["Student visas","Work visas","Family reunification"], languages:["English","Finnish","Swedish","Russian"], rating:4.8, reviews:54, price:110, description:"Focused guidance for students, researchers, and growing international families.", qualifications:["Licensed immigration adviser","MA, International Relations"], consultation:"30-minute initial consultation" },
  { id:"claire-mitchell", name:"Claire Mitchell", type:"Immigration Lawyer", country:"Canada", jurisdiction:"Ontario, Canada", experience:16, specializations:["Permanent residence","Work visas","Citizenship"], languages:["English","French"], rating:4.9, reviews:122, price:220, description:"Canadian immigration counsel for skilled workers, employers, and permanent residence applicants.", qualifications:["JD, Osgoode Hall Law School","Law Society of Ontario member"], consultation:"60-minute strategy consultation" },
  { id:"dev-patel", name:"Dev Patel", type:"Accredited Immigration Advisor", country:"Canada", jurisdiction:"Canada", experience:8, specializations:["Student visas","Permanent residence","Family reunification"], languages:["English","Hindi","Punjabi"], rating:4.7, reviews:71, price:125, description:"Thoughtful, step-by-step help with Canadian study and family immigration pathways.", qualifications:["Regulated Canadian Immigration Consultant","Graduate Diploma in Immigration Law"], consultation:"45-minute video consultation" },
  { id:"eleanor-price", name:"Eleanor Price", type:"Immigration Lawyer", country:"United Kingdom", jurisdiction:"England & Wales", experience:18, specializations:["Work visas","Family reunification","Citizenship"], languages:["English","Spanish"], rating:4.9, reviews:109, price:240, description:"Experienced adviser on UK work routes, settlement, and complex family applications.", qualifications:["LLB, King’s College London","Solicitor of England & Wales"], consultation:"60-minute online consultation" },
  { id:"omar-hassan", name:"Omar Hassan", type:"Accredited Immigration Advisor", country:"United Kingdom", jurisdiction:"United Kingdom", experience:7, specializations:["Student visas","Work visas","Residence permits"], languages:["English","Arabic","French"], rating:4.6, reviews:43, price:105, description:"Accessible UK visa support with particular experience in graduate and skilled worker routes.", qualifications:["UK immigration advice accreditation","BA, Law and Politics"], consultation:"30-minute consultation" },
  { id:"johanna-weber", name:"Johanna Weber", type:"Immigration Lawyer", country:"Germany", jurisdiction:"Germany", experience:13, specializations:["Work visas","Residence permits","Citizenship"], languages:["German","English","Polish"], rating:4.8, reviews:68, price:190, description:"Berlin-based legal guidance for employees, entrepreneurs, and long-term residents.", qualifications:["First and Second State Examination in Law","German Bar Association member"], consultation:"45-minute video consultation" },
  { id:"leon-fischer", name:"Leon Fischer", type:"Accredited Immigration Advisor", country:"Germany", jurisdiction:"Germany", experience:6, specializations:["Student visas","Work visas","Family reunification"], languages:["German","English","Turkish"], rating:4.7, reviews:39, price:95, description:"Friendly, reliable application support for newcomers navigating German bureaucracy.", qualifications:["Certified migration adviser","MA, Migration Studies"], consultation:"30-minute initial consultation" },
  { id:"sophie-campbell", name:"Sophie Campbell", type:"Immigration Lawyer", country:"Australia", jurisdiction:"New South Wales, Australia", experience:15, specializations:["Work visas","Permanent residence","Citizenship"], languages:["English","Mandarin"], rating:4.9, reviews:93, price:230, description:"Strategic Australian migration advice for skilled professionals and their families.", qualifications:["LLB, University of Sydney","Australian legal practitioner"], consultation:"60-minute strategy consultation" },
  { id:"liam-nguyen", name:"Liam Nguyen", type:"Accredited Immigration Advisor", country:"Australia", jurisdiction:"Australia", experience:10, specializations:["Student visas","Work visas","Permanent residence"], languages:["English","Vietnamese","Mandarin"], rating:4.8, reviews:76, price:140, description:"Clear and supportive migration planning for students and skilled visa applicants.", qualifications:["Registered Migration Agent","Graduate Certificate in Australian Migration Law"], consultation:"45-minute video consultation" },
  { id:"elin-lindberg", name:"Elin Lindberg", type:"Immigration Lawyer", country:"Sweden", jurisdiction:"Sweden", experience:12, specializations:["Work visas","Family reunification","Residence permits"], languages:["Swedish","English","French"], rating:4.8, reviews:64, price:175, description:"Personal, meticulous support for Swedish work permits and family residence cases.", qualifications:["LLM, Stockholm University","Swedish Bar Association member"], consultation:"45-minute video consultation" },
  { id:"gustav-nordin", name:"Gustav Nordin", type:"Accredited Immigration Advisor", country:"Sweden", jurisdiction:"Sweden", experience:7, specializations:["Student visas","Work visas","Citizenship"], languages:["Swedish","English","Arabic"], rating:4.6, reviews:41, price:100, description:"Straightforward relocation support for international students and professionals.", qualifications:["Certified migration adviser","BA, Public Administration"], consultation:"30-minute initial consultation" },
];

export const displayService = (service: string) => service === "Residence permit" ? "Residence permits" : service === "Work visa" ? "Work visas" : service;

export function profileDetails(professional: Professional) {
  const destinationCountries = professional.practiceCountries ?? [professional.country];
  const services = professional.services ?? [
    { name: "Initial immigration consultation", description: "Discuss your situation, options, documents, and practical next steps.", price: professional.price, duration: professional.consultation },
    ...professional.specializations.map((specialization, index) => ({ name: specialization.replace("visas", "visa support"), description: `Guidance on eligibility, preparation, and the application process for ${specialization.toLowerCase()}.`, price: professional.price + (index + 1) * 45, duration: "Support plan discussed after consultation" })),
  ];
  return {
    location: professional.location ?? professional.jurisdiction,
    tagline: professional.tagline ?? professional.description,
    biography: professional.biography ?? `${professional.name} is a ${professional.type.toLowerCase()} with ${professional.experience} years of experience supporting clients with immigration matters connected to ${professional.country}. Their approach is practical, careful, and focused on helping clients understand the route that fits their circumstances.`,
    completedCases: professional.completedCases ?? professional.experience * 38 + professional.reviews,
    practiceCountries: destinationCountries,
    availability: professional.availability ?? { today: professional.experience % 2 === 0, thisWeek: "2 consultation times available", next: "Tomorrow at 10:00" },
    services,
    reviews: professional.clientReviews ?? [
      { client: "Maya", rating: 5, text: "Clear, reassuring advice and a realistic plan for my application.", date: "July 2026" },
      { client: "Daniel", rating: 5, text: "Very organised and responsive. I understood every next step.", date: "May 2026" },
      { client: "Sara", rating: 4, text: "A thoughtful consultation that helped me move forward with confidence.", date: "March 2026" },
    ],
  };
}
