-- Phase 5: immutable submission, Migri, decision and completion evidence.
ALTER TYPE "CaseStatus" ADD VALUE IF NOT EXISTS 'AWAITING_MIGRI';
ALTER TYPE "CaseStatus" ADD VALUE IF NOT EXISTS 'DECISION_RECEIVED';
CREATE TYPE "MigriDecisionOutcome" AS ENUM ('POSITIVE', 'NEGATIVE', 'OTHER');
ALTER TABLE "CaseDocumentRequirement" ADD COLUMN "supplementaryRequestId" TEXT;
ALTER TABLE "CaseDocument" ADD COLUMN "supplementaryRequestId" TEXT, ADD COLUMN "migriDecisionId" TEXT;
CREATE TABLE "CaseSubmission" ("id" TEXT NOT NULL, "caseId" TEXT NOT NULL, "submittedById" TEXT NOT NULL, "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "checklist" JSONB NOT NULL, "referenceNumber" TEXT, "note" TEXT, CONSTRAINT "CaseSubmission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MigriSupplementaryRequest" ("id" TEXT NOT NULL, "caseId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "receivedAt" TIMESTAMP(3), "deadline" TIMESTAMP(3), "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MigriSupplementaryRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MigriSupplementaryResponse" ("id" TEXT NOT NULL, "supplementaryRequestId" TEXT NOT NULL, "submittedById" TEXT NOT NULL, "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "referenceNumber" TEXT, "note" TEXT, CONSTRAINT "MigriSupplementaryResponse_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MigriDecision" ("id" TEXT NOT NULL, "caseId" TEXT NOT NULL, "outcome" "MigriDecisionOutcome" NOT NULL, "decisionDate" TIMESTAMP(3) NOT NULL, "recordedById" TEXT NOT NULL, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "referenceNumber" TEXT, "note" TEXT, CONSTRAINT "MigriDecision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CaseCompletion" ("id" TEXT NOT NULL, "caseId" TEXT NOT NULL, "completedById" TEXT NOT NULL, "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "closingNote" TEXT, CONSTRAINT "CaseCompletion_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CaseSubmission_caseId_key" ON "CaseSubmission"("caseId");
CREATE UNIQUE INDEX "MigriSupplementaryResponse_supplementaryRequestId_key" ON "MigriSupplementaryResponse"("supplementaryRequestId");
CREATE UNIQUE INDEX "MigriDecision_caseId_key" ON "MigriDecision"("caseId");
CREATE UNIQUE INDEX "CaseCompletion_caseId_key" ON "CaseCompletion"("caseId");
CREATE INDEX "CaseDocumentRequirement_supplementaryRequestId_active_status_idx" ON "CaseDocumentRequirement"("supplementaryRequestId", "active", "status");
CREATE INDEX "CaseDocument_supplementaryRequestId_createdAt_idx" ON "CaseDocument"("supplementaryRequestId", "createdAt");
CREATE INDEX "MigriSupplementaryRequest_caseId_createdAt_idx" ON "MigriSupplementaryRequest"("caseId", "createdAt");
ALTER TABLE "CaseSubmission" ADD CONSTRAINT "CaseSubmission_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CaseSubmission" ADD CONSTRAINT "CaseSubmission_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MigriSupplementaryRequest" ADD CONSTRAINT "MigriSupplementaryRequest_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MigriSupplementaryRequest" ADD CONSTRAINT "MigriSupplementaryRequest_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MigriSupplementaryResponse" ADD CONSTRAINT "MigriSupplementaryResponse_supplementaryRequestId_fkey" FOREIGN KEY ("supplementaryRequestId") REFERENCES "MigriSupplementaryRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MigriSupplementaryResponse" ADD CONSTRAINT "MigriSupplementaryResponse_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MigriDecision" ADD CONSTRAINT "MigriDecision_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MigriDecision" ADD CONSTRAINT "MigriDecision_recordedById_fkey" FOREIGN KEY ("recordedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CaseCompletion" ADD CONSTRAINT "CaseCompletion_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CaseCompletion" ADD CONSTRAINT "CaseCompletion_completedById_fkey" FOREIGN KEY ("completedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CaseDocumentRequirement" ADD CONSTRAINT "CaseDocumentRequirement_supplementaryRequestId_fkey" FOREIGN KEY ("supplementaryRequestId") REFERENCES "MigriSupplementaryRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CaseDocument" ADD CONSTRAINT "CaseDocument_supplementaryRequestId_fkey" FOREIGN KEY ("supplementaryRequestId") REFERENCES "MigriSupplementaryRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CaseDocument" ADD CONSTRAINT "CaseDocument_migriDecisionId_fkey" FOREIGN KEY ("migriDecisionId") REFERENCES "MigriDecision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
