"use client";

import { use, useState } from "react";

type ScannedPage = { id: string; file: File; previewUrl?: string };

export default function PhoneScanner({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params);
  const [pages, setPages] = useState<ScannedPage[]>([]);
  const [pending, setPending] = useState<ScannedPage | null>(null);
  const [retakeIndex, setRetakeIndex] = useState<number | null>(null);
  const [message, setMessage] = useState("Scan your first page.");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const choose = (files: FileList | null) => { const file = files?.[0]; if (!file) return; if (pending?.previewUrl) URL.revokeObjectURL(pending.previewUrl); setPending({ id: crypto.randomUUID(), file, previewUrl: file.type.startsWith("image/") ? URL.createObjectURL(file) : undefined }); setMessage("Review this page before adding it."); };
  const usePage = () => { if (!pending) return; if (retakeIndex === null) setPages((current) => [...current, pending]); else setPages((current) => current.map((page, index) => { if (index !== retakeIndex) return page; if (page.previewUrl) URL.revokeObjectURL(page.previewUrl); return pending; })); setPending(null); setRetakeIndex(null); setMessage("Page added. Scan another page or send all pages to your computer."); };
  const retake = () => { if (pending?.previewUrl) URL.revokeObjectURL(pending.previewUrl); setPending(null); setMessage("Scan the page again."); };
  const beginRetake = (index: number) => { setRetakeIndex(index); setMessage(`Scan a replacement for Page ${index + 1}.`); document.getElementById("phone-page-input")?.click(); };
  const remove = (id: string) => setPages((current) => { const page = current.find((item) => item.id === id); if (page?.previewUrl) URL.revokeObjectURL(page.previewUrl); return current.filter((item) => item.id !== id); });
  const send = async () => { if (!pages.length) return; setSending(true); const form = new FormData(); pages.forEach((page, index) => { const extension = page.file.name.split(".").pop() || "jpg"; form.append("files", page.file, `phone-page-${String(index + 1).padStart(3, "0")}.${extension}`); }); const response = await fetch(`/api/document-studio/transfer/${token}/upload`, { method: "POST", body: form }); if (!response.ok) { setMessage("This transfer session is unavailable or a page is not supported."); setSending(false); return; } setSent(true); setSending(false); setMessage("Pages sent successfully. You can return to your computer."); };

  return <main className="min-h-screen bg-mist"><div className="mx-auto max-w-lg px-4 py-8 sm:px-6"><p className="text-sm font-bold uppercase tracking-[.18em] text-ocean">Secure phone scanner</p><h1 className="mt-2 text-2xl font-bold">Scan pages</h1><p className="mt-2 text-slate-600">Review every page before sending the ordered set to your computer.</p>
    {sent ? <div className="mt-8 rounded-2xl border border-teal-200 bg-teal-50 p-6 text-center"><p className="text-3xl">✓</p><p className="mt-3 font-bold text-teal-900">{message}</p></div> : <>
      {pending ? <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold">Preview page {retakeIndex === null ? pages.length + 1 : retakeIndex + 1}</h2><div className="mt-4 flex min-h-72 items-center justify-center overflow-hidden rounded-xl bg-slate-100">{pending.previewUrl ? <img src={pending.previewUrl} alt="Preview scanned page" className="max-h-[60vh] w-full object-contain"/> : <p className="font-bold text-red-700">PDF selected</p>}</div><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={retake} className="rounded-xl border border-slate-300 px-4 py-3 font-bold">Retake</button><button type="button" onClick={usePage} className="rounded-xl bg-ocean px-4 py-3 font-bold text-white">Use page</button></div></section> : <label className="mt-6 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-ocean/30 bg-white p-5 text-center shadow-sm"><span className="font-bold text-ocean">{pages.length ? "Scan another page" : "Scan Page 1"}</span><span className="mt-1 text-sm text-slate-500">Use your rear camera or choose a file</span><input id="phone-page-input" className="sr-only" type="file" accept="application/pdf,image/jpeg,image/png" capture="environment" onChange={(event) => { choose(event.target.files); event.currentTarget.value = ""; }}/></label>}
      {!!pages.length && <section className="mt-6"><h2 className="font-bold">Accepted pages ({pages.length})</h2><div className="mt-3 grid grid-cols-2 gap-3">{pages.map((page, index) => <article key={page.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex h-36 items-center justify-center bg-slate-100">{page.previewUrl ? <img src={page.previewUrl} alt={`Page ${index + 1}`} className="h-full w-full object-contain"/> : <span className="font-bold text-red-700">PDF</span>}</div><div className="p-3"><span className="text-sm font-bold">Page {index + 1}</span><div className="mt-2 flex gap-3"><button type="button" onClick={() => beginRetake(index)} className="text-xs font-semibold text-ocean">Retake</button><button type="button" onClick={() => remove(page.id)} className="text-xs font-semibold text-red-700">Remove</button></div></div></article>)}</div><button type="button" disabled={sending || Boolean(pending)} onClick={send} className="mt-5 w-full rounded-xl bg-ink px-5 py-3.5 font-bold text-white disabled:opacity-40">{sending ? "Sending pages…" : `Send ${pages.length === 1 ? "page" : `${pages.length} pages`} to computer`}</button></section>}
      <p aria-live="polite" className="mt-5 rounded-xl bg-white p-4 text-sm text-slate-600">{message}</p>
    </>}
    <p className="mt-5 text-xs leading-5 text-slate-500">This temporary transfer expires automatically. Pages are only available to the signed-in desktop session that created this connection.</p>
  </div></main>;
}
