"use client";

import { use, useEffect, useState } from "react";

async function prepareSignature(file: File) {
  const bitmap = await createImageBitmap(file); const source = document.createElement("canvas"); source.width = bitmap.width; source.height = bitmap.height; const context = source.getContext("2d"); if (!context) throw new Error("Image processing unavailable"); context.drawImage(bitmap, 0, 0); bitmap.close();
  const pixels = context.getImageData(0, 0, source.width, source.height); let left = source.width; let top = source.height; let right = -1; let bottom = -1; let darkPixels = 0;
  for (let y = 0; y < source.height; y += 1) for (let x = 0; x < source.width; x += 1) { const offset = (y * source.width + x) * 4; if (Math.min(pixels.data[offset], pixels.data[offset + 1], pixels.data[offset + 2]) < 210) { darkPixels += 1; left = Math.min(left, x); right = Math.max(right, x); top = Math.min(top, y); bottom = Math.max(bottom, y); } }
  const confidence = darkPixels / (source.width * source.height); const clean = confidence >= .0005 && confidence <= .35 && right >= left;
  const output = document.createElement("canvas"); if (clean) { const padding = Math.max(6, Math.round(Math.max(source.width, source.height) * .02)); left = Math.max(0, left - padding); top = Math.max(0, top - padding); right = Math.min(source.width - 1, right + padding); bottom = Math.min(source.height - 1, bottom + padding); output.width = right - left + 1; output.height = bottom - top + 1; } else { output.width = source.width; output.height = source.height; left = 0; top = 0; }
  const outputContext = output.getContext("2d"); if (!outputContext) throw new Error("Image processing unavailable"); outputContext.drawImage(source, left, top, output.width, output.height, 0, 0, output.width, output.height);
  if (clean) { const cleaned = outputContext.getImageData(0, 0, output.width, output.height); for (let offset = 0; offset < cleaned.data.length; offset += 4) { const lightness = Math.min(cleaned.data[offset], cleaned.data[offset + 1], cleaned.data[offset + 2]); if (lightness > 235) cleaned.data[offset + 3] = 0; } outputContext.putImageData(cleaned, 0, 0); }
  const blob = await new Promise<Blob>((resolve, reject) => output.toBlob((value) => value ? resolve(value) : reject(new Error("Could not prepare image")), "image/png")); return { file: new File([blob], "signature.png", { type: "image/png" }), cleaned: clean };
}

export default function PhoneSignatureCapture({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [signature, setSignature] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [message, setMessage] = useState("Photograph your signature on plain white paper."); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false);
  useEffect(() => { if (!signature) { setPreview(null); return; } const url = URL.createObjectURL(signature); setPreview(url); return () => URL.revokeObjectURL(url); }, [signature]);
  const choose = async (file?: File) => { if (!file) return; setMessage("Preparing signature…"); try { const result = await prepareSignature(file); setSignature(result.file); setMessage(result.cleaned ? "Background cleaned. Review your signature." : "Cleanup confidence was low, so the original detail was preserved. Review before sending."); } catch { setMessage("That photo could not be prepared. Please retake it."); } };
  const send = async () => { if (!signature) return; setSending(true); const form = new FormData(); form.set("file", signature, "signature.png"); try { const response = await fetch(`/api/document-studio/signature-transfer/${token}/upload`, { method: "POST", body: form }); if (!response.ok) { setMessage("The signature could not be sent. Please try again."); return; } setSent(true); setMessage("Signature sent. You can return to your computer."); } catch { setMessage("The signature could not be sent. Please try again."); } finally { setSending(false); } };
  return <main className="min-h-screen bg-mist"><div className="mx-auto max-w-lg px-5 py-10"><p className="text-sm font-bold uppercase tracking-widest text-ocean">Signature capture</p><h1 className="mt-2 text-2xl font-bold">Capture your signature</h1><p className="mt-2 text-slate-600">Use dark ink on plain, evenly lit paper. This temporary image returns only to your open Document Studio editor.</p>{sent ? <div className="mt-8 rounded-2xl border border-teal-200 bg-teal-50 p-6 text-center font-bold text-teal-900">{message}</div> : signature && preview ? <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Preview cleaned signature</h2><div className="mt-4 flex min-h-48 items-center justify-center rounded-xl bg-slate-100 p-4"><img src={preview} alt="Cleaned signature preview" className="max-h-44 max-w-full"/></div><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={() => { setSignature(null); setMessage("Retake your signature photo."); }} className="rounded-xl border px-4 py-3 font-bold">Retake</button><button type="button" disabled={sending} onClick={send} className="rounded-xl bg-ocean px-4 py-3 font-bold text-white disabled:opacity-50">{sending ? "Sending…" : "Use signature"}</button></div></section> : <label className="mt-7 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-ocean/30 bg-white p-5 text-center shadow-sm"><span className="font-bold text-ocean">Open phone camera</span><span className="mt-1 text-sm text-slate-500">Photograph the signature only</span><input className="sr-only" type="file" accept="image/*,.heic,.heif" capture="environment" onChange={(event) => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; void choose(file); }}/></label>}<p aria-live="polite" className="mt-5 rounded-xl bg-white p-4 text-sm text-slate-600">{message}</p><p className="mt-4 text-xs text-slate-500">The signature is temporary and is not saved to a reusable signature library.</p></div></main>;
}
